version: '3'

services:
  api:
    container_name: movies-api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      JWT_KEY: 1528dahxss
    volumes:
      - /usr/app/api/node_modules

  postgres:
    container_name: postgres
    image: postgres:10.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies

  
